<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Myself.PMS.Client.Common\Myself.PMS.Client.Common.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Controls\Myself.PMS.Client.Controls.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.IBLL\Myself.PMS.Client.IBLL.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(TargetPath) $(SolutionDir)Myself.PMS.Client.Start\bin\Debug\net8.0-windows\Modules\$(TargetFileName) /y" />
  </Target>
  
</Project>
