<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myself.PMS.Client.Assets\Myself.PMS.Client.Assets.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.BLL\Myself.PMS.Client.BLL.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Common\Myself.PMS.Client.Common.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Controls\Myself.PMS.Client.Controls.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.DAL\Myself.PMS.Client.DAL.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Utils\Myself.PMS.Client.Utils.csproj" />
  </ItemGroup>

</Project>
