<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myself.PMS.Client.Assets\Myself.PMS.Client.Assets.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Entities\Myself.PMS.Client.Entities.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.IBLL\Myself.PMS.Client.IBLL.csproj" />
    <ProjectReference Include="..\Myself.PMS.Client.Utils\Myself.PMS.Client.Utils.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(TargetPath) $(SolutionDir)Myself.PMS.Client.Start\bin\Debug\net8.0-windows\Modules\$(TargetFileName) /y" />
  </Target>
</Project>
